name: cell-counter
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.25
  - pandas=2.2
  - scikit-learn=1.2
  - opencv=4.8   # conda-forge opencv
  - pillow=10.0
  - matplotlib=3.8
  - tqdm=4.65
  - pyyaml
  - omegaconf
  - onnx
  - pip:
    # small packages installed with pip for consistency
    - albumentations>=1.4
    - tensorboard
    - seaborn
    - typeguard
    - yapf
    - black
    - pre-commit

    #install the environment with:
    #conda env create -f environment.yml
    #conda activate cell-counter
    
    # install the relevant pytorch version using:
    # CPU-only
    #conda install pytorch torchvision torchaudio cpuonly -c pytorch

    # CUDA 11.8
    #conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
